export enum intructionsTypes {
    IMPRIMIR,
    CREAR_VARIABLE,
    CREAR_OBJETO,
    ASIGNAR_VALOR,
    LISTAS, //LISTA DE DECLARACIONES
    UNITARIA,
    SI,
    ACCESS_LIST, //ACESO A LISTAS
    PARA,
    MIENTRAS,
    HACER_MIENTRAS,
    DETENER,
    CONTINUAR,
    RETORNAR,
    FUNCION,
    PROCEDIMIENTO,
    LLAMADA_FUNCION,
    LLAMADA_BLOQUE_INSTRUCCIONES,
    SWITH,
    LLAMADAS //LLAMADAS PROCEDIMIENTOS
}