import { Tip } from "./Tip";
//  ENTERO  DECIMAL  BOOLEANO  CARACTER  CADENA
export const suma : Tip[][] = [
 [Tip.ENTERO, Tip.DECIMAL, Tip.ENTERO, Tip.ENTERO, Tip.CADENA],
 [Tip.DECIMAL, Tip.DECIMAL, Tip.DECIMAL, Tip.DECIMAL, Tip.CADENA],
 [Tip.ENTERO, Tip.DECIMAL, Tip.NULO, Tip.NULO, Tip.CADENA],
 [Tip.ENTERO, Tip.DECIMAL, Tip.NULO, Tip.CADENA, Tip.CADENA],
 [Tip.CADENA, Tip.CADENA, Tip.CADENA, Tip.CADENA, Tip.CADENA]   
]

export const resta : Tip[][] = [
 [Tip.ENTERO, Tip.DECIMAL, Tip.ENTERO, Tip.ENTERO,Tip.INVALIDO],//ENTERO
 [Tip.DECIMAL, Tip.DECIMAL, Tip.DECIMAL, Tip.DECIMAL,Tip.INVALIDO],//DECIMAL
 [Tip.ENTERO, Tip.DECIMAL, Tip.NULO, Tip.NULO, Tip.INVALIDO],//BOOLEANO
 [Tip.ENTERO, Tip.DECIMAL, Tip.NULO, Tip.INVALIDO, Tip.INVALIDO],//CARACTER
 [Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO]//CADENA   
]

export const multiplicacion : Tip[][] = [
    [Tip.ENTERO, Tip.DECIMAL, Tip.INVALIDO, Tip.ENTERO,Tip.INVALIDO],//ENTERO 
    [Tip.DECIMAL, Tip.DECIMAL, Tip.INVALIDO, Tip.DECIMAL,Tip.INVALIDO],//DECIMAL
    [Tip.INVALIDO,Tip.INVALIDO,Tip.INVALIDO,Tip.INVALIDO,Tip.INVALIDO],//BOOLEANO
    [Tip.ENTERO, Tip.DECIMAL, Tip.INVALIDO, Tip.NULO,Tip.INVALIDO],//CARACTER
    [Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO,Tip.INVALIDO]//CADENA
]
//  ENTERO  DECIMAL  BOOLEANO  CARACTER  CADENA
export const division : Tip[][] = [
    [Tip.DECIMAL, Tip.DECIMAL, Tip.INVALIDO, Tip.DECIMAL, Tip.INVALIDO],//ENTERO
    [Tip.DECIMAL, Tip.DECIMAL, Tip.INVALIDO, Tip.DECIMAL, Tip.INVALIDO],//DECIMAL
    [Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO],//BOOLEANO
    [Tip.DECIMAL, Tip.DECIMAL, Tip.INVALIDO, Tip.NULO, Tip.INVALIDO],//CARACTER
    [Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO]//CADENA
]
export const potencia : Tip[][] = [
    [Tip.ENTERO, Tip.DECIMAL, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO],//ENTERO
    [Tip.DECIMAL, Tip.DECIMAL, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO],//DECIMAL
    [Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO],//BOOLEANO
    [Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO],//CARACTER
    [Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO]//CADENA
]
export const modulo : Tip[][] = [
    [Tip.DECIMAL, Tip.DECIMAL, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO],//ENTERO
    [Tip.DECIMAL, Tip.DECIMAL, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO],//DECIMAL
    [Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO],//BOOLEANO
    [Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO],//CARACTER
    [Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO, Tip.INVALIDO]//CADENA
]
export const negacionUnitaria : Tip[] = [
    Tip.ENTERO, 
    Tip.DECIMAL, 
    Tip.INVALIDO, 
    Tip.INVALIDO, 
    Tip.INVALIDO
]